sudo: required

language: python

python:
    - "3.5"

services:
    - docker

before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update -m
    - sudo apt-get -y install docker-ce

install:
    - pip install tox

script:
    - tox -c restq/tox.ini
    - docker-compose build

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker-compose push;
      fi
