sudo: required

language: python

python:
    - "3.5"

services:
    - docker

before_install:
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
    - pip install tox

script:
    - tox -c restq/tox.ini
    - docker-compose build

after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker-compose push;
      fi
