version: '3.3'
services:
  relaxq:
    image: docker2.molflow.com/relaxq/relaxq:latest
  ui:
    image: docker2.molflow.com/relaxq/ui:latest
  rabbitmq:
    image: rabbitmq:latest
  gateway:
    image: docker2.molflow.com/relaxq/gateway:latest
    ports:
      - "127.0.0.1:80:80"
